import { RxDashboard } from "react-icons/rx";
import { CgShutterstock } from "react-icons/cg";
import { MdPeopleAlt } from "react-icons/md";
import { FaConciergeBell } from "react-icons/fa";
import { TbEdit, TbReportAnalytics } from "react-icons/tb";
import { HiOutlineUserCircle } from "react-icons/hi";
import { GoSettings } from "react-icons/go";
import { GiHamburgerMenu } from "react-icons/gi";
import { AiOutlinePlus, AiFillPrinter } from "react-icons/ai";
import { CiSearch } from "react-icons/ci";
import { FiRefreshCw, FiPrinter } from "react-icons/fi";
import { TfiFilter } from "react-icons/tfi";
import { TiArrowUnsorted } from "react-icons/ti";
import { MdDeleteOutline } from "react-icons/md";
import { BiEditAlt } from "react-icons/bi";
import { RiFileShield2Line } from "react-icons/ri";
//export icon
export { RxDashboard as HomeIcon };
export { CgShutterstock as StockIcon };
export { MdPeopleAlt as PeopleIcon };
export { FaConciergeBell as BellIcon };
export { TbEdit as DrawerIcon };
export { TbReportAnalytics as ReportIcon };
export { HiOutlineUserCircle as UserIcon };
export { GoSettings as SettingsIcon };
export { GiHamburgerMenu as HumbergerIcon };
export { AiOutlinePlus as AddIcon };
export { CiSearch as SearchIcon };
export { TfiFilter as FilterIcon };
export { FiRefreshCw as RefreshIcon };
export { FiPrinter as PrintIcon };
export { TiArrowUnsorted as SortedIcon };
export { MdDeleteOutline as DeleteIcon };
export { BiEditAlt as EditIcon };
export { RiFileShield2Line as EditShieldIcon };
